### ISSUE TITLE
Problem when rebuild the children of ig Stories

### ISSUE THREAD

**Issue by omarsherifs** [YuheiNakasaka/flutter_ig_story#1]
The following error occurs when rebuilding the children of `IgStories`.
```
E/flutter (15432): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 180 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
E/flutter (15432): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (15432): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (15432): #2      PageController.page
package:flutter/…/widgets/page_view.dart:180
E/flutter (15432): #3      _IgStoriesState.initState.<anonymous closure>
package:ig_story/ig_story.dart:471
E/flutter (15432): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (15432): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (15432): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (15432): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (15432): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (15432): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (15432): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (15432): #11     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (15432): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (15432): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (15432): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (15432): #15     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (15432): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (15432): #17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (15432): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (15432): #19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (15432): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (15432):
Exited (1)
```

My app has a story future that needs to be reordered after reading or open a certain story so after I'm using `WillPopScope` to wrap the `IgStories` widget to detect the pop event of page `IgStories` widget and rebuild the children according to the new order.

**Comment by omarsherifs** [comment]
the error was adding new children to the list of `IgStories` children without clearing the old one.
